### ISSUE TITLE
conceptScheme.topConcepts should also be URL

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos#85]
ConceptScheme.concepts can be array or URL. Same should apply to topConcepts

**Comment by nichtich** [comment]
The feature to have URL in concept scheme field `concepts` or `types` is not used anyway, so better remove it instead.

@stefandesu does jskos-server, cocoda-sdk or cocoda store an URL in this field(s)? I don't think so. See https://github.com/gbv/jskos/commit/67afa072878e77d8cd93f60edcca60ea9f8d8684 for commit to remove JSKOS API URLs - ok?

**Comment by stefandesu** [comment]
As far as I can tell, strings for those fields are not supported anywhere in our applications. However, we do support it for the `schemes` field for registries in cocoda-sdk. The issue with removing it from registries is that strings are the main form for all those fields on the registry because there we actually need to know how to access it. We still use the array type to be able to restrict a registry to a set of schemes.

**Comment by stefandesu** [comment]
To be very honest, I don't see an issue with leaving something in the spec even if we don't use it. Someone else might use it and might want to use it in the future. We also don't have versioned JSON schema, I think, which is a problem if someone would want to keep using the old version.

**Comment by nichtich** [comment]
Made clear topConcepts must be a set of objects, no plain URI/URL(s).
