### ISSUE TITLE
package-lock.json: Either commit or ignore

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos#90]
```bash
❯ npm i   
npm notice created a lockfile as package-lock.json. You should commit this file.
```

npm itself recommends committing the package-lock.json file. If you don't want this, please add the file to .gitignore so that it won't always show up as an uncommitted change. Thanks!

**Comment by nichtich** [comment]
I think having the file in the repository is good for deployment but to me it looks like a burden otherwise because it changes depending on the development environment. Reading https://stackoverflow.com/a/56254478/373710 I think best practice is to commit but use `npm ci` instead of `npm install` during development. I'll change the documentation accordingly.

**Comment by nichtich** [comment]
Oh, I thought this comment referred to cocoda repository, so I did https://github.com/gbv/cocoda/commit/d42f019268277206056a626e8333ca4d5207509f

**Comment by stefandesu** [comment]
> Oh, I thought this comment referred to cocoda repository, so I did [gbv/cocoda@d42f019](https://github.com/gbv/cocoda/commit/d42f019268277206056a626e8333ca4d5207509f)

I mean the same thing applies to all npm-based repos where package-lock.json is committed, so it's no big deal.
